

CREATE TABLE ACCOUNT(
    ID UUID PRIMARY KEY,
    AMOUNT DOUBLE PRECISION,
    CUSTOMER_ID UUID,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_DATE,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_DATE
);

CREATE TABLE CUSTOMER(
    ID UUID PRIMARY KEY,
    NAME VARCHAR(100),
    DOCUMENT VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_DATE,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_DATE
);

CREATE TABLE TRANSACTION(
    ID UUID PRIMARY KEY,
    TYPE VARCHAR(10),
    AMOUNT DOUBLE PRECISION,
    RECEIVER UUID,
    PAYER UUID,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_DATE,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_DATE
);

CREATE SEQUENCE hibernate_sequence;