apiVersion: v1
kind: ReplicationController
metadata:
  name: git2consul
spec:
  replicas: 1
  selector:
    app: git2consul
  template:
    metadata:
      labels:
        app: git2consul
    spec:
      containers:
        - name: git2consul
          image: cimpress/git2consul:0.12.13
          imagePullPolicy: "IfNotPresent"
          command: ["/bin/sh", "-c", "git2consul --endpoint $CONSUL_ENDPOINT --port $CONSUL_PORT --config-file /etc/config/config.json"]
          env:
            - name: CONSUL_ENDPOINT
              value: "consul-consul-server.default.svc.cluster.local"
            - name: CONSUL_PORT
              value: "8500"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: git2consul-config
            items:
              - key: CFG
                path: config.json