apiVersion: apps/v1
kind: Deployment
metadata:
  name: stonebank-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stonebank-processor
  template:
    metadata:
      labels:
        app: stonebank-processor
    spec:
      containers:
        - name: stonebank-processor
          image: ronistone/stonebank-processor:0.0.6
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: stonebank-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 5
            periodSeconds: 20