apiVersion: apps/v1
kind: Deployment
metadata:
  name: stonebank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stonebank
  template:
    metadata:
      labels:
        app: stonebank
    spec:
      containers:
        - name: stonebank
          image: ronistone/stonebank:0.0.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: stonebank-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 5
            periodSeconds: 20