apiVersion: v1
kind: ConfigMap
metadata:
  name: stonebank-config
  labels:
    app: stonebank
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stonebank
  SPRING_DATASOURCE_USERNAME: stonebank
  SPRING_DATASOURCE_PASSWORD: stonebank